### ISSUE TITLE
Add Ability to List Products

### ISSUE THREAD

**Issue by AmerGong** [NYU-DevOps-Products-Squad/products#1]
**As a** Customer

**I need** to be able to list all products 

**So that** I can view all products

**Assumptions:**

* A call to "GET" should get the product list from the database.

**Acceptance Criteria:**
```
Given a valid URL call

When a GET request is invoked

Then the list of products is returned

Status 500 if the internal server error
```

**Comment by Xun66** [comment]
How's the scenario when customers want to search or filters products? Should we support filter or search action on products?

**Comment by Xun66** [comment]
For APIs that return multiple results, how should we handle paging issues? 
> Let's say there's 4096 products (SPU) in our database, and he wants to browse products. But he may want to see all products in several pages instead of rendering the whole list to screen at one time.

**Comment by AmerGong** [comment]
> How's the scenario when customers want to search or filters products? Should we support filter or search action on products?

This story is about "List Resources". #11 and #15 are about "Query Resources by some attribute of the Resource".

**Comment by AmerGong** [comment]
> For APIs that return multiple results, how should we handle paging issues?
> 
> > Let's say there's 4096 products (SPU) in our database, and he wants to browse products. But he may want to see all products in several pages instead of rendering the whole list to screen at one time.

If it is necessary, we can write a new story.
