### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by hanweii** [NYU-DevOps-Products-Squad/products#24]
**As a** Developer

**I need** add Continuous Integration (CI) to our repository

**So that** every Pull Requests should run both of our TDD test cases and BDD test cases

**Assumptions:**

* There is a .travis.yml file and Travis CI has been configured
* Travis CI is set up to monitor your GitHub repository for push and pull requests
* README.md file has a Travis CI badge

**Acceptance Criteria:**
```
When every time someone pushes to the master branch or submits a Pull Request
Then both TDD test cases and BDD test cases will be run
```

**Comment by zijingSun** [comment]
we need add codecov to requirement.txt, that's why we failed so many times
